export class CustomAddressFields {}
export class CustomAdministratorFields {}
export class CustomAssetFields {}
export class CustomFacetFields {}
export class CustomFacetFieldsTranslation {}
export class CustomFacetValueFields {}
export class CustomFacetValueFieldsTranslation {}
export class CustomFulfillmentFields {}
export class CustomCustomerFields {}
export class CustomOrderLineFields {}
export class CustomProductFields {}
export class CustomProductFieldsTranslation {}
export class CustomCollectionFields {}
export class CustomCollectionFieldsTranslation {}
export class CustomChannelFields {}
export class CustomProductOptionFields {}
export class CustomProductOptionFieldsTranslation {}
export class CustomProductOptionGroupFields {}
export class CustomProductOptionGroupFieldsTranslation {}
export class CustomProductVariantFields {}
export class CustomProductVariantFieldsTranslation {}
export class CustomUserFields {}
export class CustomGlobalSettingsFields {}
export class CustomOrderFields {}
export class CustomShippingMethodFields {}
export class CustomShippingMethodFieldsTranslation {}
