export class CustomAddressFields {}
export class CustomAdministratorFields {}
export class CustomAssetFields {}
export class CustomChannelFields {}
export class CustomCollectionFields {}
export class CustomCollectionFieldsTranslation {}
export class CustomCustomerFields {}
export class CustomCustomerGroupFields {}
export class CustomFacetFields {}
export class CustomFacetFieldsTranslation {}
export class CustomFacetValueFields {}
export class CustomFacetValueFieldsTranslation {}
export class CustomFulfillmentFields {}
export class CustomGlobalSettingsFields {}
export class CustomOrderFields {}
export class CustomOrderLineFields {}
export class CustomPaymentMethodFields {}
export class CustomPaymentMethodFieldsTranslation {}
export class CustomProductFields {}
export class CustomProductFieldsTranslation {}
export class CustomProductOptionFields {}
export class CustomProductOptionFieldsTranslation {}
export class CustomProductOptionGroupFields {}
export class CustomProductOptionGroupFieldsTranslation {}
export class CustomProductVariantFields {}
export class CustomProductVariantFieldsTranslation {}
export class CustomProductVariantPriceFields {}
export class CustomPromotionFields {}
export class CustomPromotionFieldsTranslation {}
export class CustomRegionFields {}
export class CustomRegionFieldsTranslation {}
export class CustomSellerFields {}
export class CustomShippingMethodFields {}
export class CustomShippingMethodFieldsTranslation {}
export class CustomStockLocationFields {}
export class CustomTaxCategoryFields {}
export class CustomTaxRateFields {}
export class CustomUserFields {}
export class CustomZoneFields {}
