// This file was generated by the build-public-api.ts script
export * from './components/address-card/address-card.component';
export * from './components/customer-detail/customer-detail.component';
export * from './components/customer-list/customer-list.component';
export * from './components/customer-status-label/customer-status-label.component';
export * from './customer.module';
export * from './customer.routes';
export * from './providers/routing/customer-resolver';
