name: 'Verdaccio Publish Action'
description: 'This action will deploy your package to a local Verdaccio Registry'
author: 'GitHub'
inputs:
  debug:
    description: 'npm debug level'
    default: '-ddd'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.debug }}
