export const PLUGIN_INIT_OPTIONS = Symbol('DASHBOARD_PLUGIN_INIT_OPTIONS');
export const loggerCtx = 'DashboardPlugin';

export const notIndexableEntities = [
    'GlobalSearchIndexItem',
    'AuthenticationMethod',
    'NativeAuthenticationMethod',
    'Tag',
    'OrderLineReference',
    'FulfillmentLine',
    'Refund',
    'RefundLine',
    'Payment',
    'Surcharge',
    'OrderModification',
    'ShippingLine',
    'StockMovement',
    'Allocation',
    'Cancellation',
    'ExternalAuthenticationMethod',
    'GlobalSettings',
    'Session',
    'AnonymousSession',
    'StockAdjustment',
    'Release',
    'HistoryEntry',
    'OrderHistoryEntry',
    'CustomerHistoryEntry',
    'SearchIndexItem',
    'JobRecord',
    'AuthenticatedSession',
    'ScheduledTaskRecord',
    'ProductOption',
    'ProductOptionGroup', // TODO: Remove when https://github.com/vendure-ecommerce/vendure/issues/3489 is done
    'CollectionAsset',
    'FacetValue',
    'OrderLine',
    'ProductAsset',
    'ProductVariantPrice',
    'StockLevel',
];
