export type ActionBarLocationId =
    | 'administrator-detail'
    | 'administrator-list'
    | 'asset-detail'
    | 'asset-list'
    | 'channel-detail'
    | 'channel-list'
    | 'collection-detail'
    | 'collection-list'
    | 'country-detail'
    | 'country-list'
    | 'customer-detail'
    | 'customer-list'
    | 'customer-group-list'
    | 'facet-detail'
    | 'facet-list'
    | 'global-setting-detail'
    | 'system-status'
    | 'job-list'
    | 'order-detail'
    | 'order-list'
    | 'payment-method-detail'
    | 'payment-method-list'
    | 'product-detail'
    | 'product-list'
    | 'promotion-detail'
    | 'promotion-list'
    | 'role-detail'
    | 'role-list'
    | 'shipping-method-detail'
    | 'shipping-method-list'
    | 'tax-category-detail'
    | 'tax-category-list'
    | 'tax-rate-detail'
    | 'tax-rate-list'
    | 'zone-list';

export type UIExtensionLocationId = ActionBarLocationId;
