@startuml
!include theme.puml
title Vendure Class Diagram

class Channel {
    name: string
    defaultLanguageCode: LanguageCode
    defaultCurrencyCode: CurrencyCode
}
class User {
    identifier: string
    passwordHash: string
    roles: UserRole[]
}
class Customer {
    user: User
    addresses: Address[]
    orders: Order[]
}
class Administrator {
    user: User
}
class Role {
    name: string
    permissions: Permission[]
    user: User
    channel: Channel
}
enum Permission {
    CreateCatalog
    ReadCatalog
    UpdateCatalog
    DeleteCatalog
    CreateUser
    ...etc
}
class Address {
}
class Product {
    variants: ProductVariant[]
}
class ProductOptionGroup
class ProductOption {
    group: ProductOptionGroup
}
class ProductVariant {
    sku: string
    price: ProductVariantPrice[]
}
class ProductVariantPrice {
    value: number
    currencyCode: CurrencyCode
}
class Order
class OrderItem {
    order: Order
    productVariant: ProductVariant
}
class OrderItemUnit {
    orderItem: OrderItem
}
class Adjustment {
    orderItemUnit?: OrderItemUnit
    orderItem?: OrderItem
    order?: Order
}
enum AdjustmentType {
    Tax
    Shipping
    Promotion
}
class AdjustmentSource {
    type: AdjustmentType
}
class Facet {
    values: FacetValue[]
}
class FacetValue {
}
class Category {
}

Customer --  User
Administrator -- User
User o-- Role
Role o-- "1..*" Permission
Role -- Channel
Customer *-- "0..*" Address
Product *-- "1..*" ProductVariant
ProductOptionGroup *-- "1..*" ProductOption
Product o-- "0..*" ProductOptionGroup
ProductVariant o-- "0..*" ProductOption
ProductVariant o-- "0..*" FacetValue
Facet *-- "1..*" FacetValue
Category o-- "1..*" FacetValue
Customer *-- "0..*" Order
OrderItem - ProductVariant
Order *-- OrderItem
Order -- Channel
OrderItem *-- OrderItemUnit
OrderItemUnit o-- Adjustment
OrderItem o-- Adjustment
Order o-- Adjustment
Adjustment - AdjustmentType
AdjustmentSource - AdjustmentType
AdjustmentSource o-- Channel
Product o-- Channel
ProductVariant *-- "1..*" ProductVariantPrice
ProductVariantPrice o-- Channel

@enduml
