@startuml
!define BLACK   #363D5D
!define LINE    #1a3164
!define BACKGROUND #b9cefc
!define BORDER  #e58e26
!define GREEN   #66aa66
!define BLUE  #4067af
!define BLUE_LIGHT  #c6dbff

' Base Setting
skinparam Shadowing false
skinparam backgroundColor #fff
skinparam ComponentStyle uml2
skinparam TitleFontSize 18
skinparam Padding 3

skinparam Default {
  FontName  'Segoe UI'
  FontColor BLACK
  FontSize  14
  FontStyle plain
}

skinparam Class {
  BackgroundColor BLUE_LIGHT
  BorderColor BLACK
}

skinparam Component {
  ArrowColor LINE
  BorderColor BLACK
  BackgroundColor BACKGROUND
}

skinparam Note {
  ArrowThickness 2
  ArrowColor LINE
  ActorBorderThickness 1
  LifeLineBorderColor GREEN
  BorderColor #666666
  BackgroundColor #eeeeee
}

skinparam Interface {
  BorderColor BLACK
  BackgroundColor BLUE
}

skinparam Activity {
  FontColor white
  AttributeFontColor white
  BackgroundColor BLUE
  BorderColor BLACK
  ArrowColor #222266
}

skinparam ActivityDiamond {
  BackgroundColor BLUE_LIGHT
  BorderColor BLACK
  FontColor BLACK
}

skinparam Sequence {
  ArrowThickness 2
  ArrowColor LINE
  ActorBorderThickness 1
  LifeLineBorderColor GREEN
  ParticipantBorderThickness 0
  BorderColor BORDER
  BackgroundColor BACKGROUND
}

skinparam State {
  FontStyle bold
  BackgroundColor BLUE_LIGHT
  BorderColor BLACK
}

skinparam Participant {
  BackgroundColor BLACK
  BorderColor BORDER
  FontColor #FFFFFF
}

skinparam Actor {
  BackgroundColor BLACK
  BorderColor BLACK
}
@enduml
