/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedZonesZonesRouteImport } from './routes/_authenticated/_zones/zones'
import { Route as AuthenticatedTaxRatesTaxRatesRouteImport } from './routes/_authenticated/_tax-rates/tax-rates'
import { Route as AuthenticatedTaxCategoriesTaxCategoriesRouteImport } from './routes/_authenticated/_tax-categories/tax-categories'
import { Route as AuthenticatedSystemScheduledTasksRouteImport } from './routes/_authenticated/_system/scheduled-tasks'
import { Route as AuthenticatedSystemJobQueueRouteImport } from './routes/_authenticated/_system/job-queue'
import { Route as AuthenticatedSystemHealthchecksRouteImport } from './routes/_authenticated/_system/healthchecks'
import { Route as AuthenticatedStockLocationsStockLocationsRouteImport } from './routes/_authenticated/_stock-locations/stock-locations'
import { Route as AuthenticatedShippingMethodsShippingMethodsRouteImport } from './routes/_authenticated/_shipping-methods/shipping-methods'
import { Route as AuthenticatedSellersSellersRouteImport } from './routes/_authenticated/_sellers/sellers'
import { Route as AuthenticatedRolesRolesRouteImport } from './routes/_authenticated/_roles/roles'
import { Route as AuthenticatedPromotionsPromotionsRouteImport } from './routes/_authenticated/_promotions/promotions'
import { Route as AuthenticatedProfileProfileRouteImport } from './routes/_authenticated/_profile/profile'
import { Route as AuthenticatedProductsProductsRouteImport } from './routes/_authenticated/_products/products'
import { Route as AuthenticatedProductVariantsProductVariantsRouteImport } from './routes/_authenticated/_product-variants/product-variants'
import { Route as AuthenticatedPaymentMethodsPaymentMethodsRouteImport } from './routes/_authenticated/_payment-methods/payment-methods'
import { Route as AuthenticatedOrdersOrdersRouteImport } from './routes/_authenticated/_orders/orders'
import { Route as AuthenticatedGlobalSettingsGlobalSettingsRouteImport } from './routes/_authenticated/_global-settings/global-settings'
import { Route as AuthenticatedFacetsFacetsRouteImport } from './routes/_authenticated/_facets/facets'
import { Route as AuthenticatedCustomersCustomersRouteImport } from './routes/_authenticated/_customers/customers'
import { Route as AuthenticatedCustomerGroupsCustomerGroupsRouteImport } from './routes/_authenticated/_customer-groups/customer-groups'
import { Route as AuthenticatedCountriesCountriesRouteImport } from './routes/_authenticated/_countries/countries'
import { Route as AuthenticatedCollectionsCollectionsRouteImport } from './routes/_authenticated/_collections/collections'
import { Route as AuthenticatedChannelsChannelsRouteImport } from './routes/_authenticated/_channels/channels'
import { Route as AuthenticatedAssetsAssetsRouteImport } from './routes/_authenticated/_assets/assets'
import { Route as AuthenticatedAdministratorsAdministratorsRouteImport } from './routes/_authenticated/_administrators/administrators'
import { Route as AuthenticatedZonesZonesIdRouteImport } from './routes/_authenticated/_zones/zones_.$id'
import { Route as AuthenticatedTaxRatesTaxRatesIdRouteImport } from './routes/_authenticated/_tax-rates/tax-rates_.$id'
import { Route as AuthenticatedTaxCategoriesTaxCategoriesIdRouteImport } from './routes/_authenticated/_tax-categories/tax-categories_.$id'
import { Route as AuthenticatedStockLocationsStockLocationsIdRouteImport } from './routes/_authenticated/_stock-locations/stock-locations_.$id'
import { Route as AuthenticatedShippingMethodsShippingMethodsIdRouteImport } from './routes/_authenticated/_shipping-methods/shipping-methods_.$id'
import { Route as AuthenticatedSellersSellersIdRouteImport } from './routes/_authenticated/_sellers/sellers_.$id'
import { Route as AuthenticatedRolesRolesIdRouteImport } from './routes/_authenticated/_roles/roles_.$id'
import { Route as AuthenticatedPromotionsPromotionsIdRouteImport } from './routes/_authenticated/_promotions/promotions_.$id'
import { Route as AuthenticatedProductsProductsIdRouteImport } from './routes/_authenticated/_products/products_.$id'
import { Route as AuthenticatedProductVariantsProductVariantsIdRouteImport } from './routes/_authenticated/_product-variants/product-variants_.$id'
import { Route as AuthenticatedPaymentMethodsPaymentMethodsIdRouteImport } from './routes/_authenticated/_payment-methods/payment-methods_.$id'
import { Route as AuthenticatedOrdersOrdersIdRouteImport } from './routes/_authenticated/_orders/orders_.$id'
import { Route as AuthenticatedFacetsFacetsIdRouteImport } from './routes/_authenticated/_facets/facets_.$id'
import { Route as AuthenticatedCustomersCustomersIdRouteImport } from './routes/_authenticated/_customers/customers_.$id'
import { Route as AuthenticatedCustomerGroupsCustomerGroupsIdRouteImport } from './routes/_authenticated/_customer-groups/customer-groups_.$id'
import { Route as AuthenticatedCountriesCountriesIdRouteImport } from './routes/_authenticated/_countries/countries_.$id'
import { Route as AuthenticatedCollectionsCollectionsIdRouteImport } from './routes/_authenticated/_collections/collections_.$id'
import { Route as AuthenticatedChannelsChannelsIdRouteImport } from './routes/_authenticated/_channels/channels_.$id'
import { Route as AuthenticatedAssetsAssetsIdRouteImport } from './routes/_authenticated/_assets/assets_.$id'
import { Route as AuthenticatedAdministratorsAdministratorsIdRouteImport } from './routes/_authenticated/_administrators/administrators_.$id'
import { Route as AuthenticatedProductsProductsIdVariantsRouteImport } from './routes/_authenticated/_products/products_.$id_.variants'
import { Route as AuthenticatedOrdersOrdersDraftIdRouteImport } from './routes/_authenticated/_orders/orders_.draft.$id'
import { Route as AuthenticatedOrdersOrdersIdModifyRouteImport } from './routes/_authenticated/_orders/orders_.$id_.modify'
import { Route as AuthenticatedProductsProductsProductIdOptionGroupsIdRouteImport } from './routes/_authenticated/_products/products_.$productId.option-groups.$id'
import { Route as AuthenticatedOrdersOrdersAggregateOrderIdSellerOrdersSellerOrderIdRouteImport } from './routes/_authenticated/_orders/orders_.$aggregateOrderId_.seller-orders.$sellerOrderId'
import { Route as AuthenticatedFacetsFacetsFacetIdValuesIdRouteImport } from './routes/_authenticated/_facets/facets_.$facetId.values_.$id'
import { Route as AuthenticatedProductsProductsProductIdOptionGroupsProductOptionGroupIdOptionsIdRouteImport } from './routes/_authenticated/_products/products_.$productId.option-groups.$productOptionGroupId.options_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedZonesZonesRoute = AuthenticatedZonesZonesRouteImport.update({
  id: '/_zones/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTaxRatesTaxRatesRoute =
  AuthenticatedTaxRatesTaxRatesRouteImport.update({
    id: '/_tax-rates/tax-rates',
    path: '/tax-rates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTaxCategoriesTaxCategoriesRoute =
  AuthenticatedTaxCategoriesTaxCategoriesRouteImport.update({
    id: '/_tax-categories/tax-categories',
    path: '/tax-categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemScheduledTasksRoute =
  AuthenticatedSystemScheduledTasksRouteImport.update({
    id: '/_system/scheduled-tasks',
    path: '/scheduled-tasks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemJobQueueRoute =
  AuthenticatedSystemJobQueueRouteImport.update({
    id: '/_system/job-queue',
    path: '/job-queue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemHealthchecksRoute =
  AuthenticatedSystemHealthchecksRouteImport.update({
    id: '/_system/healthchecks',
    path: '/healthchecks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStockLocationsStockLocationsRoute =
  AuthenticatedStockLocationsStockLocationsRouteImport.update({
    id: '/_stock-locations/stock-locations',
    path: '/stock-locations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShippingMethodsShippingMethodsRoute =
  AuthenticatedShippingMethodsShippingMethodsRouteImport.update({
    id: '/_shipping-methods/shipping-methods',
    path: '/shipping-methods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSellersSellersRoute =
  AuthenticatedSellersSellersRouteImport.update({
    id: '/_sellers/sellers',
    path: '/sellers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRolesRolesRoute = AuthenticatedRolesRolesRouteImport.update({
  id: '/_roles/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPromotionsPromotionsRoute =
  AuthenticatedPromotionsPromotionsRouteImport.update({
    id: '/_promotions/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileProfileRoute =
  AuthenticatedProfileProfileRouteImport.update({
    id: '/_profile/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsProductsRoute =
  AuthenticatedProductsProductsRouteImport.update({
    id: '/_products/products',
    path: '/products',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductVariantsProductVariantsRoute =
  AuthenticatedProductVariantsProductVariantsRouteImport.update({
    id: '/_product-variants/product-variants',
    path: '/product-variants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentMethodsPaymentMethodsRoute =
  AuthenticatedPaymentMethodsPaymentMethodsRouteImport.update({
    id: '/_payment-methods/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrdersRoute =
  AuthenticatedOrdersOrdersRouteImport.update({
    id: '/_orders/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGlobalSettingsGlobalSettingsRoute =
  AuthenticatedGlobalSettingsGlobalSettingsRouteImport.update({
    id: '/_global-settings/global-settings',
    path: '/global-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacetsFacetsRoute =
  AuthenticatedFacetsFacetsRouteImport.update({
    id: '/_facets/facets',
    path: '/facets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCustomersRoute =
  AuthenticatedCustomersCustomersRouteImport.update({
    id: '/_customers/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerGroupsCustomerGroupsRoute =
  AuthenticatedCustomerGroupsCustomerGroupsRouteImport.update({
    id: '/_customer-groups/customer-groups',
    path: '/customer-groups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCountriesCountriesRoute =
  AuthenticatedCountriesCountriesRouteImport.update({
    id: '/_countries/countries',
    path: '/countries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsCollectionsRoute =
  AuthenticatedCollectionsCollectionsRouteImport.update({
    id: '/_collections/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChannelsChannelsRoute =
  AuthenticatedChannelsChannelsRouteImport.update({
    id: '/_channels/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsAssetsRoute =
  AuthenticatedAssetsAssetsRouteImport.update({
    id: '/_assets/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministratorsAdministratorsRoute =
  AuthenticatedAdministratorsAdministratorsRouteImport.update({
    id: '/_administrators/administrators',
    path: '/administrators',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedZonesZonesIdRoute =
  AuthenticatedZonesZonesIdRouteImport.update({
    id: '/_zones/zones_/$id',
    path: '/zones/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTaxRatesTaxRatesIdRoute =
  AuthenticatedTaxRatesTaxRatesIdRouteImport.update({
    id: '/_tax-rates/tax-rates_/$id',
    path: '/tax-rates/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTaxCategoriesTaxCategoriesIdRoute =
  AuthenticatedTaxCategoriesTaxCategoriesIdRouteImport.update({
    id: '/_tax-categories/tax-categories_/$id',
    path: '/tax-categories/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStockLocationsStockLocationsIdRoute =
  AuthenticatedStockLocationsStockLocationsIdRouteImport.update({
    id: '/_stock-locations/stock-locations_/$id',
    path: '/stock-locations/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShippingMethodsShippingMethodsIdRoute =
  AuthenticatedShippingMethodsShippingMethodsIdRouteImport.update({
    id: '/_shipping-methods/shipping-methods_/$id',
    path: '/shipping-methods/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSellersSellersIdRoute =
  AuthenticatedSellersSellersIdRouteImport.update({
    id: '/_sellers/sellers_/$id',
    path: '/sellers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRolesRolesIdRoute =
  AuthenticatedRolesRolesIdRouteImport.update({
    id: '/_roles/roles_/$id',
    path: '/roles/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPromotionsPromotionsIdRoute =
  AuthenticatedPromotionsPromotionsIdRouteImport.update({
    id: '/_promotions/promotions_/$id',
    path: '/promotions/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsProductsIdRoute =
  AuthenticatedProductsProductsIdRouteImport.update({
    id: '/_products/products_/$id',
    path: '/products/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductVariantsProductVariantsIdRoute =
  AuthenticatedProductVariantsProductVariantsIdRouteImport.update({
    id: '/_product-variants/product-variants_/$id',
    path: '/product-variants/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentMethodsPaymentMethodsIdRoute =
  AuthenticatedPaymentMethodsPaymentMethodsIdRouteImport.update({
    id: '/_payment-methods/payment-methods_/$id',
    path: '/payment-methods/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrdersIdRoute =
  AuthenticatedOrdersOrdersIdRouteImport.update({
    id: '/_orders/orders_/$id',
    path: '/orders/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFacetsFacetsIdRoute =
  AuthenticatedFacetsFacetsIdRouteImport.update({
    id: '/_facets/facets_/$id',
    path: '/facets/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCustomersIdRoute =
  AuthenticatedCustomersCustomersIdRouteImport.update({
    id: '/_customers/customers_/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerGroupsCustomerGroupsIdRoute =
  AuthenticatedCustomerGroupsCustomerGroupsIdRouteImport.update({
    id: '/_customer-groups/customer-groups_/$id',
    path: '/customer-groups/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCountriesCountriesIdRoute =
  AuthenticatedCountriesCountriesIdRouteImport.update({
    id: '/_countries/countries_/$id',
    path: '/countries/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsCollectionsIdRoute =
  AuthenticatedCollectionsCollectionsIdRouteImport.update({
    id: '/_collections/collections_/$id',
    path: '/collections/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChannelsChannelsIdRoute =
  AuthenticatedChannelsChannelsIdRouteImport.update({
    id: '/_channels/channels_/$id',
    path: '/channels/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsAssetsIdRoute =
  AuthenticatedAssetsAssetsIdRouteImport.update({
    id: '/_assets/assets_/$id',
    path: '/assets/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministratorsAdministratorsIdRoute =
  AuthenticatedAdministratorsAdministratorsIdRouteImport.update({
    id: '/_administrators/administrators_/$id',
    path: '/administrators/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsProductsIdVariantsRoute =
  AuthenticatedProductsProductsIdVariantsRouteImport.update({
    id: '/_products/products_/$id_/variants',
    path: '/products/$id/variants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrdersDraftIdRoute =
  AuthenticatedOrdersOrdersDraftIdRouteImport.update({
    id: '/_orders/orders_/draft/$id',
    path: '/orders/draft/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrdersIdModifyRoute =
  AuthenticatedOrdersOrdersIdModifyRouteImport.update({
    id: '/_orders/orders_/$id_/modify',
    path: '/orders/$id/modify',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsProductsProductIdOptionGroupsIdRoute =
  AuthenticatedProductsProductsProductIdOptionGroupsIdRouteImport.update({
    id: '/_products/products_/$productId/option-groups/$id',
    path: '/products/$productId/option-groups/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrdersAggregateOrderIdSellerOrdersSellerOrderIdRoute =
  AuthenticatedOrdersOrdersAggregateOrderIdSellerOrdersSellerOrderIdRouteImport.update(
    {
      id: '/_orders/orders_/$aggregateOrderId_/seller-orders/$sellerOrderId',
      path: '/orders/$aggregateOrderId/seller-orders/$sellerOrderId',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedFacetsFacetsFacetIdValuesIdRoute =
  AuthenticatedFacetsFacetsFacetIdValuesIdRouteImport.update({
    id: '/_facets/facets_/$facetId/values_/$id',
    path: '/facets/$facetId/values/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsProductsProductIdOptionGroupsProductOptionGroupIdOptionsIdRoute =
  AuthenticatedProductsProductsProductIdOptionGroupsProductOptionGroupIdOptionsIdRouteImport.update(
    {
      id: '/_products/products_/$productId/option-groups/$productOptionGroupId/options_/$id',
      path: '/products/$productId/option-groups/$productOptionGroupId/options/$id',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/administrators': typeof AuthenticatedAdministratorsAdministratorsRoute
  '/assets': typeof AuthenticatedAssetsAssetsRoute
  '/channels': typeof AuthenticatedChannelsChannelsRoute
  '/collections': typeof AuthenticatedCollectionsCollectionsRoute
  '/countries': typeof AuthenticatedCountriesCountriesRoute
  '/customer-groups': typeof AuthenticatedCustomerGroupsCustomerGroupsRoute
  '/customers': typeof AuthenticatedCustomersCustomersRoute
  '/facets': typeof AuthenticatedFacetsFacetsRoute
  '/global-settings': typeof AuthenticatedGlobalSettingsGlobalSettingsRoute
  '/orders': typeof AuthenticatedOrdersOrdersRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsPaymentMethodsRoute
  '/product-variants': typeof AuthenticatedProductVariantsProductVariantsRoute
  '/products': typeof AuthenticatedProductsProductsRoute
  '/profile': typeof AuthenticatedProfileProfileRoute
  '/promotions': typeof AuthenticatedPromotionsPromotionsRoute
  '/roles': typeof AuthenticatedRolesRolesRoute
  '/sellers': typeof AuthenticatedSellersSellersRoute
  '/shipping-methods': typeof AuthenticatedShippingMethodsShippingMethodsRoute
  '/stock-locations': typeof AuthenticatedStockLocationsStockLocationsRoute
  '/healthchecks': typeof AuthenticatedSystemHealthchecksRoute
  '/job-queue': typeof AuthenticatedSystemJobQueueRoute
  '/scheduled-tasks': typeof AuthenticatedSystemScheduledTasksRoute
  '/tax-categories': typeof AuthenticatedTaxCategoriesTaxCategoriesRoute
  '/tax-rates': typeof AuthenticatedTaxRatesTaxRatesRoute
  '/zones': typeof AuthenticatedZonesZonesRoute
  '/administrators/$id': typeof AuthenticatedAdministratorsAdministratorsIdRoute
  '/assets/$id': typeof AuthenticatedAssetsAssetsIdRoute
  '/channels/$id': typeof AuthenticatedChannelsChannelsIdRoute
  '/collections/$id': typeof AuthenticatedCollectionsCollectionsIdRoute
  '/countries/$id': typeof AuthenticatedCountriesCountriesIdRoute
  '/customer-groups/$id': typeof AuthenticatedCustomerGroupsCustomerGroupsIdRoute
  '/customers/$id': typeof AuthenticatedCustomersCustomersIdRoute
  '/facets/$id': typeof AuthenticatedFacetsFacetsIdRoute
  '/orders/$id': typeof AuthenticatedOrdersOrdersIdRoute
  '/payment-methods/$id': typeof AuthenticatedPaymentMethodsPaymentMethodsIdRoute
  '/product-variants/$id': typeof AuthenticatedProductVariantsProductVariantsIdRoute
  '/products/$id': typeof AuthenticatedProductsProductsIdRoute
  '/promotions/$id': typeof AuthenticatedPromotionsPromotionsIdRoute
  '/roles/$id': typeof AuthenticatedRolesRolesIdRoute
  '/sellers/$id': typeof AuthenticatedSellersSellersIdRoute
  '/shipping-methods/$id': typeof AuthenticatedShippingMethodsShippingMethodsIdRoute
  '/stock-locations/$id': typeof AuthenticatedStockLocationsStockLocationsIdRoute
  '/tax-categories/$id': typeof AuthenticatedTaxCategoriesTaxCategoriesIdRoute
  '/tax-rates/$id': typeof AuthenticatedTaxRatesTaxRatesIdRoute
  '/zones/$id': typeof AuthenticatedZonesZonesIdRoute
  '/orders/$id/modify': typeof AuthenticatedOrdersOrdersIdModifyRoute
  '/orders/draft/$id': typeof AuthenticatedOrdersOrdersDraftIdRoute
  '/products/$id/variants': typeof AuthenticatedProductsProductsIdVariantsRoute
  '/facets/$facetId/values/$id': typeof AuthenticatedFacetsFacetsFacetIdValuesIdRoute
  '/orders/$aggregateOrderId/seller-orders/$sellerOrderId': typeof AuthenticatedOrdersOrdersAggregateOrderIdSellerOrdersSellerOrderIdRoute
  '/products/$productId/option-groups/$id': typeof AuthenticatedProductsProductsProductIdOptionGroupsIdRoute
  '/products/$productId/option-groups/$productOptionGroupId/options/$id': typeof AuthenticatedProductsProductsProductIdOptionGroupsProductOptionGroupIdOptionsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/administrators': typeof AuthenticatedAdministratorsAdministratorsRoute
  '/assets': typeof AuthenticatedAssetsAssetsRoute
  '/channels': typeof AuthenticatedChannelsChannelsRoute
  '/collections': typeof AuthenticatedCollectionsCollectionsRoute
  '/countries': typeof AuthenticatedCountriesCountriesRoute
  '/customer-groups': typeof AuthenticatedCustomerGroupsCustomerGroupsRoute
  '/customers': typeof AuthenticatedCustomersCustomersRoute
  '/facets': typeof AuthenticatedFacetsFacetsRoute
  '/global-settings': typeof AuthenticatedGlobalSettingsGlobalSettingsRoute
  '/orders': typeof AuthenticatedOrdersOrdersRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsPaymentMethodsRoute
  '/product-variants': typeof AuthenticatedProductVariantsProductVariantsRoute
  '/products': typeof AuthenticatedProductsProductsRoute
  '/profile': typeof AuthenticatedProfileProfileRoute
  '/promotions': typeof AuthenticatedPromotionsPromotionsRoute
  '/roles': typeof AuthenticatedRolesRolesRoute
  '/sellers': typeof AuthenticatedSellersSellersRoute
  '/shipping-methods': typeof AuthenticatedShippingMethodsShippingMethodsRoute
  '/stock-locations': typeof AuthenticatedStockLocationsStockLocationsRoute
  '/healthchecks': typeof AuthenticatedSystemHealthchecksRoute
  '/job-queue': typeof AuthenticatedSystemJobQueueRoute
  '/scheduled-tasks': typeof AuthenticatedSystemScheduledTasksRoute
  '/tax-categories': typeof AuthenticatedTaxCategoriesTaxCategoriesRoute
  '/tax-rates': typeof AuthenticatedTaxRatesTaxRatesRoute
  '/zones': typeof AuthenticatedZonesZonesRoute
  '/administrators/$id': typeof AuthenticatedAdministratorsAdministratorsIdRoute
  '/assets/$id': typeof AuthenticatedAssetsAssetsIdRoute
  '/channels/$id': typeof AuthenticatedChannelsChannelsIdRoute
  '/collections/$id': typeof AuthenticatedCollectionsCollectionsIdRoute
  '/countries/$id': typeof AuthenticatedCountriesCountriesIdRoute
  '/customer-groups/$id': typeof AuthenticatedCustomerGroupsCustomerGroupsIdRoute
  '/customers/$id': typeof AuthenticatedCustomersCustomersIdRoute
  '/facets/$id': typeof AuthenticatedFacetsFacetsIdRoute
  '/orders/$id': typeof AuthenticatedOrdersOrdersIdRoute
  '/payment-methods/$id': typeof AuthenticatedPaymentMethodsPaymentMethodsIdRoute
  '/product-variants/$id': typeof AuthenticatedProductVariantsProductVariantsIdRoute
  '/products/$id': typeof AuthenticatedProductsProductsIdRoute
  '/promotions/$id': typeof AuthenticatedPromotionsPromotionsIdRoute
  '/roles/$id': typeof AuthenticatedRolesRolesIdRoute
  '/sellers/$id': typeof AuthenticatedSellersSellersIdRoute
  '/shipping-methods/$id': typeof AuthenticatedShippingMethodsShippingMethodsIdRoute
  '/stock-locations/$id': typeof AuthenticatedStockLocationsStockLocationsIdRoute
  '/tax-categories/$id': typeof AuthenticatedTaxCategoriesTaxCategoriesIdRoute
  '/tax-rates/$id': typeof AuthenticatedTaxRatesTaxRatesIdRoute
  '/zones/$id': typeof AuthenticatedZonesZonesIdRoute
  '/orders/$id/modify': typeof AuthenticatedOrdersOrdersIdModifyRoute
  '/orders/draft/$id': typeof AuthenticatedOrdersOrdersDraftIdRoute
  '/products/$id/variants': typeof AuthenticatedProductsProductsIdVariantsRoute
  '/facets/$facetId/values/$id': typeof AuthenticatedFacetsFacetsFacetIdValuesIdRoute
  '/orders/$aggregateOrderId/seller-orders/$sellerOrderId': typeof AuthenticatedOrdersOrdersAggregateOrderIdSellerOrdersSellerOrderIdRoute
  '/products/$productId/option-groups/$id': typeof AuthenticatedProductsProductsProductIdOptionGroupsIdRoute
  '/products/$productId/option-groups/$productOptionGroupId/options/$id': typeof AuthenticatedProductsProductsProductIdOptionGroupsProductOptionGroupIdOptionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_administrators/administrators': typeof AuthenticatedAdministratorsAdministratorsRoute
  '/_authenticated/_assets/assets': typeof AuthenticatedAssetsAssetsRoute
  '/_authenticated/_channels/channels': typeof AuthenticatedChannelsChannelsRoute
  '/_authenticated/_collections/collections': typeof AuthenticatedCollectionsCollectionsRoute
  '/_authenticated/_countries/countries': typeof AuthenticatedCountriesCountriesRoute
  '/_authenticated/_customer-groups/customer-groups': typeof AuthenticatedCustomerGroupsCustomerGroupsRoute
  '/_authenticated/_customers/customers': typeof AuthenticatedCustomersCustomersRoute
  '/_authenticated/_facets/facets': typeof AuthenticatedFacetsFacetsRoute
  '/_authenticated/_global-settings/global-settings': typeof AuthenticatedGlobalSettingsGlobalSettingsRoute
  '/_authenticated/_orders/orders': typeof AuthenticatedOrdersOrdersRoute
  '/_authenticated/_payment-methods/payment-methods': typeof AuthenticatedPaymentMethodsPaymentMethodsRoute
  '/_authenticated/_product-variants/product-variants': typeof AuthenticatedProductVariantsProductVariantsRoute
  '/_authenticated/_products/products': typeof AuthenticatedProductsProductsRoute
  '/_authenticated/_profile/profile': typeof AuthenticatedProfileProfileRoute
  '/_authenticated/_promotions/promotions': typeof AuthenticatedPromotionsPromotionsRoute
  '/_authenticated/_roles/roles': typeof AuthenticatedRolesRolesRoute
  '/_authenticated/_sellers/sellers': typeof AuthenticatedSellersSellersRoute
  '/_authenticated/_shipping-methods/shipping-methods': typeof AuthenticatedShippingMethodsShippingMethodsRoute
  '/_authenticated/_stock-locations/stock-locations': typeof AuthenticatedStockLocationsStockLocationsRoute
  '/_authenticated/_system/healthchecks': typeof AuthenticatedSystemHealthchecksRoute
  '/_authenticated/_system/job-queue': typeof AuthenticatedSystemJobQueueRoute
  '/_authenticated/_system/scheduled-tasks': typeof AuthenticatedSystemScheduledTasksRoute
  '/_authenticated/_tax-categories/tax-categories': typeof AuthenticatedTaxCategoriesTaxCategoriesRoute
  '/_authenticated/_tax-rates/tax-rates': typeof AuthenticatedTaxRatesTaxRatesRoute
  '/_authenticated/_zones/zones': typeof AuthenticatedZonesZonesRoute
  '/_authenticated/_administrators/administrators_/$id': typeof AuthenticatedAdministratorsAdministratorsIdRoute
  '/_authenticated/_assets/assets_/$id': typeof AuthenticatedAssetsAssetsIdRoute
  '/_authenticated/_channels/channels_/$id': typeof AuthenticatedChannelsChannelsIdRoute
  '/_authenticated/_collections/collections_/$id': typeof AuthenticatedCollectionsCollectionsIdRoute
  '/_authenticated/_countries/countries_/$id': typeof AuthenticatedCountriesCountriesIdRoute
  '/_authenticated/_customer-groups/customer-groups_/$id': typeof AuthenticatedCustomerGroupsCustomerGroupsIdRoute
  '/_authenticated/_customers/customers_/$id': typeof AuthenticatedCustomersCustomersIdRoute
  '/_authenticated/_facets/facets_/$id': typeof AuthenticatedFacetsFacetsIdRoute
  '/_authenticated/_orders/orders_/$id': typeof AuthenticatedOrdersOrdersIdRoute
  '/_authenticated/_payment-methods/payment-methods_/$id': typeof AuthenticatedPaymentMethodsPaymentMethodsIdRoute
  '/_authenticated/_product-variants/product-variants_/$id': typeof AuthenticatedProductVariantsProductVariantsIdRoute
  '/_authenticated/_products/products_/$id': typeof AuthenticatedProductsProductsIdRoute
  '/_authenticated/_promotions/promotions_/$id': typeof AuthenticatedPromotionsPromotionsIdRoute
  '/_authenticated/_roles/roles_/$id': typeof AuthenticatedRolesRolesIdRoute
  '/_authenticated/_sellers/sellers_/$id': typeof AuthenticatedSellersSellersIdRoute
  '/_authenticated/_shipping-methods/shipping-methods_/$id': typeof AuthenticatedShippingMethodsShippingMethodsIdRoute
  '/_authenticated/_stock-locations/stock-locations_/$id': typeof AuthenticatedStockLocationsStockLocationsIdRoute
  '/_authenticated/_tax-categories/tax-categories_/$id': typeof AuthenticatedTaxCategoriesTaxCategoriesIdRoute
  '/_authenticated/_tax-rates/tax-rates_/$id': typeof AuthenticatedTaxRatesTaxRatesIdRoute
  '/_authenticated/_zones/zones_/$id': typeof AuthenticatedZonesZonesIdRoute
  '/_authenticated/_orders/orders_/$id_/modify': typeof AuthenticatedOrdersOrdersIdModifyRoute
  '/_authenticated/_orders/orders_/draft/$id': typeof AuthenticatedOrdersOrdersDraftIdRoute
  '/_authenticated/_products/products_/$id_/variants': typeof AuthenticatedProductsProductsIdVariantsRoute
  '/_authenticated/_facets/facets_/$facetId/values_/$id': typeof AuthenticatedFacetsFacetsFacetIdValuesIdRoute
  '/_authenticated/_orders/orders_/$aggregateOrderId_/seller-orders/$sellerOrderId': typeof AuthenticatedOrdersOrdersAggregateOrderIdSellerOrdersSellerOrderIdRoute
  '/_authenticated/_products/products_/$productId/option-groups/$id': typeof AuthenticatedProductsProductsProductIdOptionGroupsIdRoute
  '/_authenticated/_products/products_/$productId/option-groups/$productOptionGroupId/options_/$id': typeof AuthenticatedProductsProductsProductIdOptionGroupsProductOptionGroupIdOptionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/administrators'
    | '/assets'
    | '/channels'
    | '/collections'
    | '/countries'
    | '/customer-groups'
    | '/customers'
    | '/facets'
    | '/global-settings'
    | '/orders'
    | '/payment-methods'
    | '/product-variants'
    | '/products'
    | '/profile'
    | '/promotions'
    | '/roles'
    | '/sellers'
    | '/shipping-methods'
    | '/stock-locations'
    | '/healthchecks'
    | '/job-queue'
    | '/scheduled-tasks'
    | '/tax-categories'
    | '/tax-rates'
    | '/zones'
    | '/administrators/$id'
    | '/assets/$id'
    | '/channels/$id'
    | '/collections/$id'
    | '/countries/$id'
    | '/customer-groups/$id'
    | '/customers/$id'
    | '/facets/$id'
    | '/orders/$id'
    | '/payment-methods/$id'
    | '/product-variants/$id'
    | '/products/$id'
    | '/promotions/$id'
    | '/roles/$id'
    | '/sellers/$id'
    | '/shipping-methods/$id'
    | '/stock-locations/$id'
    | '/tax-categories/$id'
    | '/tax-rates/$id'
    | '/zones/$id'
    | '/orders/$id/modify'
    | '/orders/draft/$id'
    | '/products/$id/variants'
    | '/facets/$facetId/values/$id'
    | '/orders/$aggregateOrderId/seller-orders/$sellerOrderId'
    | '/products/$productId/option-groups/$id'
    | '/products/$productId/option-groups/$productOptionGroupId/options/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/administrators'
    | '/assets'
    | '/channels'
    | '/collections'
    | '/countries'
    | '/customer-groups'
    | '/customers'
    | '/facets'
    | '/global-settings'
    | '/orders'
    | '/payment-methods'
    | '/product-variants'
    | '/products'
    | '/profile'
    | '/promotions'
    | '/roles'
    | '/sellers'
    | '/shipping-methods'
    | '/stock-locations'
    | '/healthchecks'
    | '/job-queue'
    | '/scheduled-tasks'
    | '/tax-categories'
    | '/tax-rates'
    | '/zones'
    | '/administrators/$id'
    | '/assets/$id'
    | '/channels/$id'
    | '/collections/$id'
    | '/countries/$id'
    | '/customer-groups/$id'
    | '/customers/$id'
    | '/facets/$id'
    | '/orders/$id'
    | '/payment-methods/$id'
    | '/product-variants/$id'
    | '/products/$id'
    | '/promotions/$id'
    | '/roles/$id'
    | '/sellers/$id'
    | '/shipping-methods/$id'
    | '/stock-locations/$id'
    | '/tax-categories/$id'
    | '/tax-rates/$id'
    | '/zones/$id'
    | '/orders/$id/modify'
    | '/orders/draft/$id'
    | '/products/$id/variants'
    | '/facets/$facetId/values/$id'
    | '/orders/$aggregateOrderId/seller-orders/$sellerOrderId'
    | '/products/$productId/option-groups/$id'
    | '/products/$productId/option-groups/$productOptionGroupId/options/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/_administrators/administrators'
    | '/_authenticated/_assets/assets'
    | '/_authenticated/_channels/channels'
    | '/_authenticated/_collections/collections'
    | '/_authenticated/_countries/countries'
    | '/_authenticated/_customer-groups/customer-groups'
    | '/_authenticated/_customers/customers'
    | '/_authenticated/_facets/facets'
    | '/_authenticated/_global-settings/global-settings'
    | '/_authenticated/_orders/orders'
    | '/_authenticated/_payment-methods/payment-methods'
    | '/_authenticated/_product-variants/product-variants'
    | '/_authenticated/_products/products'
    | '/_authenticated/_profile/profile'
    | '/_authenticated/_promotions/promotions'
    | '/_authenticated/_roles/roles'
    | '/_authenticated/_sellers/sellers'
    | '/_authenticated/_shipping-methods/shipping-methods'
    | '/_authenticated/_stock-locations/stock-locations'
    | '/_authenticated/_system/healthchecks'
    | '/_authenticated/_system/job-queue'
    | '/_authenticated/_system/scheduled-tasks'
    | '/_authenticated/_tax-categories/tax-categories'
    | '/_authenticated/_tax-rates/tax-rates'
    | '/_authenticated/_zones/zones'
    | '/_authenticated/_administrators/administrators_/$id'
    | '/_authenticated/_assets/assets_/$id'
    | '/_authenticated/_channels/channels_/$id'
    | '/_authenticated/_collections/collections_/$id'
    | '/_authenticated/_countries/countries_/$id'
    | '/_authenticated/_customer-groups/customer-groups_/$id'
    | '/_authenticated/_customers/customers_/$id'
    | '/_authenticated/_facets/facets_/$id'
    | '/_authenticated/_orders/orders_/$id'
    | '/_authenticated/_payment-methods/payment-methods_/$id'
    | '/_authenticated/_product-variants/product-variants_/$id'
    | '/_authenticated/_products/products_/$id'
    | '/_authenticated/_promotions/promotions_/$id'
    | '/_authenticated/_roles/roles_/$id'
    | '/_authenticated/_sellers/sellers_/$id'
    | '/_authenticated/_shipping-methods/shipping-methods_/$id'
    | '/_authenticated/_stock-locations/stock-locations_/$id'
    | '/_authenticated/_tax-categories/tax-categories_/$id'
    | '/_authenticated/_tax-rates/tax-rates_/$id'
    | '/_authenticated/_zones/zones_/$id'
    | '/_authenticated/_orders/orders_/$id_/modify'
    | '/_authenticated/_orders/orders_/draft/$id'
    | '/_authenticated/_products/products_/$id_/variants'
    | '/_authenticated/_facets/facets_/$facetId/values_/$id'
    | '/_authenticated/_orders/orders_/$aggregateOrderId_/seller-orders/$sellerOrderId'
    | '/_authenticated/_products/products_/$productId/option-groups/$id'
    | '/_authenticated/_products/products_/$productId/option-groups/$productOptionGroupId/options_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_zones/zones': {
      id: '/_authenticated/_zones/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof AuthenticatedZonesZonesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_tax-rates/tax-rates': {
      id: '/_authenticated/_tax-rates/tax-rates'
      path: '/tax-rates'
      fullPath: '/tax-rates'
      preLoaderRoute: typeof AuthenticatedTaxRatesTaxRatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_tax-categories/tax-categories': {
      id: '/_authenticated/_tax-categories/tax-categories'
      path: '/tax-categories'
      fullPath: '/tax-categories'
      preLoaderRoute: typeof AuthenticatedTaxCategoriesTaxCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_system/scheduled-tasks': {
      id: '/_authenticated/_system/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/scheduled-tasks'
      preLoaderRoute: typeof AuthenticatedSystemScheduledTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_system/job-queue': {
      id: '/_authenticated/_system/job-queue'
      path: '/job-queue'
      fullPath: '/job-queue'
      preLoaderRoute: typeof AuthenticatedSystemJobQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_system/healthchecks': {
      id: '/_authenticated/_system/healthchecks'
      path: '/healthchecks'
      fullPath: '/healthchecks'
      preLoaderRoute: typeof AuthenticatedSystemHealthchecksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_stock-locations/stock-locations': {
      id: '/_authenticated/_stock-locations/stock-locations'
      path: '/stock-locations'
      fullPath: '/stock-locations'
      preLoaderRoute: typeof AuthenticatedStockLocationsStockLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shipping-methods/shipping-methods': {
      id: '/_authenticated/_shipping-methods/shipping-methods'
      path: '/shipping-methods'
      fullPath: '/shipping-methods'
      preLoaderRoute: typeof AuthenticatedShippingMethodsShippingMethodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_sellers/sellers': {
      id: '/_authenticated/_sellers/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof AuthenticatedSellersSellersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_roles/roles': {
      id: '/_authenticated/_roles/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_promotions/promotions': {
      id: '/_authenticated/_promotions/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsPromotionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_profile/profile': {
      id: '/_authenticated/_profile/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_products/products': {
      id: '/_authenticated/_products/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_product-variants/product-variants': {
      id: '/_authenticated/_product-variants/product-variants'
      path: '/product-variants'
      fullPath: '/product-variants'
      preLoaderRoute: typeof AuthenticatedProductVariantsProductVariantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_payment-methods/payment-methods': {
      id: '/_authenticated/_payment-methods/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof AuthenticatedPaymentMethodsPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_orders/orders': {
      id: '/_authenticated/_orders/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_global-settings/global-settings': {
      id: '/_authenticated/_global-settings/global-settings'
      path: '/global-settings'
      fullPath: '/global-settings'
      preLoaderRoute: typeof AuthenticatedGlobalSettingsGlobalSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_facets/facets': {
      id: '/_authenticated/_facets/facets'
      path: '/facets'
      fullPath: '/facets'
      preLoaderRoute: typeof AuthenticatedFacetsFacetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_customers/customers': {
      id: '/_authenticated/_customers/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_customer-groups/customer-groups': {
      id: '/_authenticated/_customer-groups/customer-groups'
      path: '/customer-groups'
      fullPath: '/customer-groups'
      preLoaderRoute: typeof AuthenticatedCustomerGroupsCustomerGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_countries/countries': {
      id: '/_authenticated/_countries/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof AuthenticatedCountriesCountriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_collections/collections': {
      id: '/_authenticated/_collections/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_channels/channels': {
      id: '/_authenticated/_channels/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_assets/assets': {
      id: '/_authenticated/_assets/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_administrators/administrators': {
      id: '/_authenticated/_administrators/administrators'
      path: '/administrators'
      fullPath: '/administrators'
      preLoaderRoute: typeof AuthenticatedAdministratorsAdministratorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_zones/zones_/$id': {
      id: '/_authenticated/_zones/zones_/$id'
      path: '/zones/$id'
      fullPath: '/zones/$id'
      preLoaderRoute: typeof AuthenticatedZonesZonesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_tax-rates/tax-rates_/$id': {
      id: '/_authenticated/_tax-rates/tax-rates_/$id'
      path: '/tax-rates/$id'
      fullPath: '/tax-rates/$id'
      preLoaderRoute: typeof AuthenticatedTaxRatesTaxRatesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_tax-categories/tax-categories_/$id': {
      id: '/_authenticated/_tax-categories/tax-categories_/$id'
      path: '/tax-categories/$id'
      fullPath: '/tax-categories/$id'
      preLoaderRoute: typeof AuthenticatedTaxCategoriesTaxCategoriesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_stock-locations/stock-locations_/$id': {
      id: '/_authenticated/_stock-locations/stock-locations_/$id'
      path: '/stock-locations/$id'
      fullPath: '/stock-locations/$id'
      preLoaderRoute: typeof AuthenticatedStockLocationsStockLocationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shipping-methods/shipping-methods_/$id': {
      id: '/_authenticated/_shipping-methods/shipping-methods_/$id'
      path: '/shipping-methods/$id'
      fullPath: '/shipping-methods/$id'
      preLoaderRoute: typeof AuthenticatedShippingMethodsShippingMethodsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_sellers/sellers_/$id': {
      id: '/_authenticated/_sellers/sellers_/$id'
      path: '/sellers/$id'
      fullPath: '/sellers/$id'
      preLoaderRoute: typeof AuthenticatedSellersSellersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_roles/roles_/$id': {
      id: '/_authenticated/_roles/roles_/$id'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof AuthenticatedRolesRolesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_promotions/promotions_/$id': {
      id: '/_authenticated/_promotions/promotions_/$id'
      path: '/promotions/$id'
      fullPath: '/promotions/$id'
      preLoaderRoute: typeof AuthenticatedPromotionsPromotionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_products/products_/$id': {
      id: '/_authenticated/_products/products_/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsProductsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_product-variants/product-variants_/$id': {
      id: '/_authenticated/_product-variants/product-variants_/$id'
      path: '/product-variants/$id'
      fullPath: '/product-variants/$id'
      preLoaderRoute: typeof AuthenticatedProductVariantsProductVariantsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_payment-methods/payment-methods_/$id': {
      id: '/_authenticated/_payment-methods/payment-methods_/$id'
      path: '/payment-methods/$id'
      fullPath: '/payment-methods/$id'
      preLoaderRoute: typeof AuthenticatedPaymentMethodsPaymentMethodsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_orders/orders_/$id': {
      id: '/_authenticated/_orders/orders_/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_facets/facets_/$id': {
      id: '/_authenticated/_facets/facets_/$id'
      path: '/facets/$id'
      fullPath: '/facets/$id'
      preLoaderRoute: typeof AuthenticatedFacetsFacetsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_customers/customers_/$id': {
      id: '/_authenticated/_customers/customers_/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_customer-groups/customer-groups_/$id': {
      id: '/_authenticated/_customer-groups/customer-groups_/$id'
      path: '/customer-groups/$id'
      fullPath: '/customer-groups/$id'
      preLoaderRoute: typeof AuthenticatedCustomerGroupsCustomerGroupsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_countries/countries_/$id': {
      id: '/_authenticated/_countries/countries_/$id'
      path: '/countries/$id'
      fullPath: '/countries/$id'
      preLoaderRoute: typeof AuthenticatedCountriesCountriesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_collections/collections_/$id': {
      id: '/_authenticated/_collections/collections_/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_channels/channels_/$id': {
      id: '/_authenticated/_channels/channels_/$id'
      path: '/channels/$id'
      fullPath: '/channels/$id'
      preLoaderRoute: typeof AuthenticatedChannelsChannelsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_assets/assets_/$id': {
      id: '/_authenticated/_assets/assets_/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsAssetsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_administrators/administrators_/$id': {
      id: '/_authenticated/_administrators/administrators_/$id'
      path: '/administrators/$id'
      fullPath: '/administrators/$id'
      preLoaderRoute: typeof AuthenticatedAdministratorsAdministratorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_products/products_/$id_/variants': {
      id: '/_authenticated/_products/products_/$id_/variants'
      path: '/products/$id/variants'
      fullPath: '/products/$id/variants'
      preLoaderRoute: typeof AuthenticatedProductsProductsIdVariantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_orders/orders_/draft/$id': {
      id: '/_authenticated/_orders/orders_/draft/$id'
      path: '/orders/draft/$id'
      fullPath: '/orders/draft/$id'
      preLoaderRoute: typeof AuthenticatedOrdersOrdersDraftIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_orders/orders_/$id_/modify': {
      id: '/_authenticated/_orders/orders_/$id_/modify'
      path: '/orders/$id/modify'
      fullPath: '/orders/$id/modify'
      preLoaderRoute: typeof AuthenticatedOrdersOrdersIdModifyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_products/products_/$productId/option-groups/$id': {
      id: '/_authenticated/_products/products_/$productId/option-groups/$id'
      path: '/products/$productId/option-groups/$id'
      fullPath: '/products/$productId/option-groups/$id'
      preLoaderRoute: typeof AuthenticatedProductsProductsProductIdOptionGroupsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_orders/orders_/$aggregateOrderId_/seller-orders/$sellerOrderId': {
      id: '/_authenticated/_orders/orders_/$aggregateOrderId_/seller-orders/$sellerOrderId'
      path: '/orders/$aggregateOrderId/seller-orders/$sellerOrderId'
      fullPath: '/orders/$aggregateOrderId/seller-orders/$sellerOrderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrdersAggregateOrderIdSellerOrdersSellerOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_facets/facets_/$facetId/values_/$id': {
      id: '/_authenticated/_facets/facets_/$facetId/values_/$id'
      path: '/facets/$facetId/values/$id'
      fullPath: '/facets/$facetId/values/$id'
      preLoaderRoute: typeof AuthenticatedFacetsFacetsFacetIdValuesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_products/products_/$productId/option-groups/$productOptionGroupId/options_/$id': {
      id: '/_authenticated/_products/products_/$productId/option-groups/$productOptionGroupId/options_/$id'
      path: '/products/$productId/option-groups/$productOptionGroupId/options/$id'
      fullPath: '/products/$productId/option-groups/$productOptionGroupId/options/$id'
      preLoaderRoute: typeof AuthenticatedProductsProductsProductIdOptionGroupsProductOptionGroupIdOptionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdministratorsAdministratorsRoute: typeof AuthenticatedAdministratorsAdministratorsRoute
  AuthenticatedAssetsAssetsRoute: typeof AuthenticatedAssetsAssetsRoute
  AuthenticatedChannelsChannelsRoute: typeof AuthenticatedChannelsChannelsRoute
  AuthenticatedCollectionsCollectionsRoute: typeof AuthenticatedCollectionsCollectionsRoute
  AuthenticatedCountriesCountriesRoute: typeof AuthenticatedCountriesCountriesRoute
  AuthenticatedCustomerGroupsCustomerGroupsRoute: typeof AuthenticatedCustomerGroupsCustomerGroupsRoute
  AuthenticatedCustomersCustomersRoute: typeof AuthenticatedCustomersCustomersRoute
  AuthenticatedFacetsFacetsRoute: typeof AuthenticatedFacetsFacetsRoute
  AuthenticatedGlobalSettingsGlobalSettingsRoute: typeof AuthenticatedGlobalSettingsGlobalSettingsRoute
  AuthenticatedOrdersOrdersRoute: typeof AuthenticatedOrdersOrdersRoute
  AuthenticatedPaymentMethodsPaymentMethodsRoute: typeof AuthenticatedPaymentMethodsPaymentMethodsRoute
  AuthenticatedProductVariantsProductVariantsRoute: typeof AuthenticatedProductVariantsProductVariantsRoute
  AuthenticatedProductsProductsRoute: typeof AuthenticatedProductsProductsRoute
  AuthenticatedProfileProfileRoute: typeof AuthenticatedProfileProfileRoute
  AuthenticatedPromotionsPromotionsRoute: typeof AuthenticatedPromotionsPromotionsRoute
  AuthenticatedRolesRolesRoute: typeof AuthenticatedRolesRolesRoute
  AuthenticatedSellersSellersRoute: typeof AuthenticatedSellersSellersRoute
  AuthenticatedShippingMethodsShippingMethodsRoute: typeof AuthenticatedShippingMethodsShippingMethodsRoute
  AuthenticatedStockLocationsStockLocationsRoute: typeof AuthenticatedStockLocationsStockLocationsRoute
  AuthenticatedSystemHealthchecksRoute: typeof AuthenticatedSystemHealthchecksRoute
  AuthenticatedSystemJobQueueRoute: typeof AuthenticatedSystemJobQueueRoute
  AuthenticatedSystemScheduledTasksRoute: typeof AuthenticatedSystemScheduledTasksRoute
  AuthenticatedTaxCategoriesTaxCategoriesRoute: typeof AuthenticatedTaxCategoriesTaxCategoriesRoute
  AuthenticatedTaxRatesTaxRatesRoute: typeof AuthenticatedTaxRatesTaxRatesRoute
  AuthenticatedZonesZonesRoute: typeof AuthenticatedZonesZonesRoute
  AuthenticatedAdministratorsAdministratorsIdRoute: typeof AuthenticatedAdministratorsAdministratorsIdRoute
  AuthenticatedAssetsAssetsIdRoute: typeof AuthenticatedAssetsAssetsIdRoute
  AuthenticatedChannelsChannelsIdRoute: typeof AuthenticatedChannelsChannelsIdRoute
  AuthenticatedCollectionsCollectionsIdRoute: typeof AuthenticatedCollectionsCollectionsIdRoute
  AuthenticatedCountriesCountriesIdRoute: typeof AuthenticatedCountriesCountriesIdRoute
  AuthenticatedCustomerGroupsCustomerGroupsIdRoute: typeof AuthenticatedCustomerGroupsCustomerGroupsIdRoute
  AuthenticatedCustomersCustomersIdRoute: typeof AuthenticatedCustomersCustomersIdRoute
  AuthenticatedFacetsFacetsIdRoute: typeof AuthenticatedFacetsFacetsIdRoute
  AuthenticatedOrdersOrdersIdRoute: typeof AuthenticatedOrdersOrdersIdRoute
  AuthenticatedPaymentMethodsPaymentMethodsIdRoute: typeof AuthenticatedPaymentMethodsPaymentMethodsIdRoute
  AuthenticatedProductVariantsProductVariantsIdRoute: typeof AuthenticatedProductVariantsProductVariantsIdRoute
  AuthenticatedProductsProductsIdRoute: typeof AuthenticatedProductsProductsIdRoute
  AuthenticatedPromotionsPromotionsIdRoute: typeof AuthenticatedPromotionsPromotionsIdRoute
  AuthenticatedRolesRolesIdRoute: typeof AuthenticatedRolesRolesIdRoute
  AuthenticatedSellersSellersIdRoute: typeof AuthenticatedSellersSellersIdRoute
  AuthenticatedShippingMethodsShippingMethodsIdRoute: typeof AuthenticatedShippingMethodsShippingMethodsIdRoute
  AuthenticatedStockLocationsStockLocationsIdRoute: typeof AuthenticatedStockLocationsStockLocationsIdRoute
  AuthenticatedTaxCategoriesTaxCategoriesIdRoute: typeof AuthenticatedTaxCategoriesTaxCategoriesIdRoute
  AuthenticatedTaxRatesTaxRatesIdRoute: typeof AuthenticatedTaxRatesTaxRatesIdRoute
  AuthenticatedZonesZonesIdRoute: typeof AuthenticatedZonesZonesIdRoute
  AuthenticatedOrdersOrdersIdModifyRoute: typeof AuthenticatedOrdersOrdersIdModifyRoute
  AuthenticatedOrdersOrdersDraftIdRoute: typeof AuthenticatedOrdersOrdersDraftIdRoute
  AuthenticatedProductsProductsIdVariantsRoute: typeof AuthenticatedProductsProductsIdVariantsRoute
  AuthenticatedFacetsFacetsFacetIdValuesIdRoute: typeof AuthenticatedFacetsFacetsFacetIdValuesIdRoute
  AuthenticatedOrdersOrdersAggregateOrderIdSellerOrdersSellerOrderIdRoute: typeof AuthenticatedOrdersOrdersAggregateOrderIdSellerOrdersSellerOrderIdRoute
  AuthenticatedProductsProductsProductIdOptionGroupsIdRoute: typeof AuthenticatedProductsProductsProductIdOptionGroupsIdRoute
  AuthenticatedProductsProductsProductIdOptionGroupsProductOptionGroupIdOptionsIdRoute: typeof AuthenticatedProductsProductsProductIdOptionGroupsProductOptionGroupIdOptionsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdministratorsAdministratorsRoute:
    AuthenticatedAdministratorsAdministratorsRoute,
  AuthenticatedAssetsAssetsRoute: AuthenticatedAssetsAssetsRoute,
  AuthenticatedChannelsChannelsRoute: AuthenticatedChannelsChannelsRoute,
  AuthenticatedCollectionsCollectionsRoute:
    AuthenticatedCollectionsCollectionsRoute,
  AuthenticatedCountriesCountriesRoute: AuthenticatedCountriesCountriesRoute,
  AuthenticatedCustomerGroupsCustomerGroupsRoute:
    AuthenticatedCustomerGroupsCustomerGroupsRoute,
  AuthenticatedCustomersCustomersRoute: AuthenticatedCustomersCustomersRoute,
  AuthenticatedFacetsFacetsRoute: AuthenticatedFacetsFacetsRoute,
  AuthenticatedGlobalSettingsGlobalSettingsRoute:
    AuthenticatedGlobalSettingsGlobalSettingsRoute,
  AuthenticatedOrdersOrdersRoute: AuthenticatedOrdersOrdersRoute,
  AuthenticatedPaymentMethodsPaymentMethodsRoute:
    AuthenticatedPaymentMethodsPaymentMethodsRoute,
  AuthenticatedProductVariantsProductVariantsRoute:
    AuthenticatedProductVariantsProductVariantsRoute,
  AuthenticatedProductsProductsRoute: AuthenticatedProductsProductsRoute,
  AuthenticatedProfileProfileRoute: AuthenticatedProfileProfileRoute,
  AuthenticatedPromotionsPromotionsRoute:
    AuthenticatedPromotionsPromotionsRoute,
  AuthenticatedRolesRolesRoute: AuthenticatedRolesRolesRoute,
  AuthenticatedSellersSellersRoute: AuthenticatedSellersSellersRoute,
  AuthenticatedShippingMethodsShippingMethodsRoute:
    AuthenticatedShippingMethodsShippingMethodsRoute,
  AuthenticatedStockLocationsStockLocationsRoute:
    AuthenticatedStockLocationsStockLocationsRoute,
  AuthenticatedSystemHealthchecksRoute: AuthenticatedSystemHealthchecksRoute,
  AuthenticatedSystemJobQueueRoute: AuthenticatedSystemJobQueueRoute,
  AuthenticatedSystemScheduledTasksRoute:
    AuthenticatedSystemScheduledTasksRoute,
  AuthenticatedTaxCategoriesTaxCategoriesRoute:
    AuthenticatedTaxCategoriesTaxCategoriesRoute,
  AuthenticatedTaxRatesTaxRatesRoute: AuthenticatedTaxRatesTaxRatesRoute,
  AuthenticatedZonesZonesRoute: AuthenticatedZonesZonesRoute,
  AuthenticatedAdministratorsAdministratorsIdRoute:
    AuthenticatedAdministratorsAdministratorsIdRoute,
  AuthenticatedAssetsAssetsIdRoute: AuthenticatedAssetsAssetsIdRoute,
  AuthenticatedChannelsChannelsIdRoute: AuthenticatedChannelsChannelsIdRoute,
  AuthenticatedCollectionsCollectionsIdRoute:
    AuthenticatedCollectionsCollectionsIdRoute,
  AuthenticatedCountriesCountriesIdRoute:
    AuthenticatedCountriesCountriesIdRoute,
  AuthenticatedCustomerGroupsCustomerGroupsIdRoute:
    AuthenticatedCustomerGroupsCustomerGroupsIdRoute,
  AuthenticatedCustomersCustomersIdRoute:
    AuthenticatedCustomersCustomersIdRoute,
  AuthenticatedFacetsFacetsIdRoute: AuthenticatedFacetsFacetsIdRoute,
  AuthenticatedOrdersOrdersIdRoute: AuthenticatedOrdersOrdersIdRoute,
  AuthenticatedPaymentMethodsPaymentMethodsIdRoute:
    AuthenticatedPaymentMethodsPaymentMethodsIdRoute,
  AuthenticatedProductVariantsProductVariantsIdRoute:
    AuthenticatedProductVariantsProductVariantsIdRoute,
  AuthenticatedProductsProductsIdRoute: AuthenticatedProductsProductsIdRoute,
  AuthenticatedPromotionsPromotionsIdRoute:
    AuthenticatedPromotionsPromotionsIdRoute,
  AuthenticatedRolesRolesIdRoute: AuthenticatedRolesRolesIdRoute,
  AuthenticatedSellersSellersIdRoute: AuthenticatedSellersSellersIdRoute,
  AuthenticatedShippingMethodsShippingMethodsIdRoute:
    AuthenticatedShippingMethodsShippingMethodsIdRoute,
  AuthenticatedStockLocationsStockLocationsIdRoute:
    AuthenticatedStockLocationsStockLocationsIdRoute,
  AuthenticatedTaxCategoriesTaxCategoriesIdRoute:
    AuthenticatedTaxCategoriesTaxCategoriesIdRoute,
  AuthenticatedTaxRatesTaxRatesIdRoute: AuthenticatedTaxRatesTaxRatesIdRoute,
  AuthenticatedZonesZonesIdRoute: AuthenticatedZonesZonesIdRoute,
  AuthenticatedOrdersOrdersIdModifyRoute:
    AuthenticatedOrdersOrdersIdModifyRoute,
  AuthenticatedOrdersOrdersDraftIdRoute: AuthenticatedOrdersOrdersDraftIdRoute,
  AuthenticatedProductsProductsIdVariantsRoute:
    AuthenticatedProductsProductsIdVariantsRoute,
  AuthenticatedFacetsFacetsFacetIdValuesIdRoute:
    AuthenticatedFacetsFacetsFacetIdValuesIdRoute,
  AuthenticatedOrdersOrdersAggregateOrderIdSellerOrdersSellerOrderIdRoute:
    AuthenticatedOrdersOrdersAggregateOrderIdSellerOrdersSellerOrderIdRoute,
  AuthenticatedProductsProductsProductIdOptionGroupsIdRoute:
    AuthenticatedProductsProductsProductIdOptionGroupsIdRoute,
  AuthenticatedProductsProductsProductIdOptionGroupsProductOptionGroupIdOptionsIdRoute:
    AuthenticatedProductsProductsProductIdOptionGroupsProductOptionGroupIdOptionsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
